### ISSUE TITLE
Section numbers

### ISSUE THREAD

**Issue by rauschma** [nagaozen/markdown-it-toc-done-right#24]
FWIW: with this CSS, you get section numbers (for sections and subsections; subsubsections etc. can be supported analogously).

```css
.table-of-contents {
  counter-reset: toc-section;
}
.table-of-contents > ul {
  list-style: none;
}

.table-of-contents > ul > li > a:before {
  counter-increment: toc-section;
  content: counter(toc-section) "\2002";
}
.table-of-contents > ul > li > a {
  counter-reset: toc-subsection;
}

.table-of-contents > ul > li > ul {
  list-style: none;
}
.table-of-contents > ul > li > ul > li > a:before {
  counter-increment: toc-subsection;
  content: counter(toc-section) "." counter(toc-subsection) "\2002";
}
```

Default:

```
1. Introduction
  1. About the topic
  2. Tips
2. First steps
  1. Getting started
```

With the CSS and `{listType: 'ul'}`:

```
1  Introduction
  1.1  About the topic
  2.1  Tips
2  First steps
  2.1  Getting started
```
