### ISSUE TITLE
Disable numbering?

### ISSUE THREAD

**Issue by chmorgan** [nagaozen/markdown-it-toc-done-right#4]
Is there a way to disable numbering? I’m working on fixing the markdown-it-hierarchy plugin and the approach that seems to make the most sense is to change that plugin to modify the header text during a core phase to add in the hierarchy text, like “1.1” or “2.”, prefixing it with the existing header text. But this means that there are duplicate numbers in the toc.

Am I missing the option to disable the numbering?

**Comment by nagaozen** [comment]
I'm unsure about what you are talking about. This plug-in just output's an `ol` or `ul` list `html` tree. If you don't like ordered list, you may want to change it to unordered list through `listType` option.

Also, if the only effect you are pursuing is adding prefixes like 1, 1.1, 1.2, you may get this with this:

```css
ol { counter-reset: list-item; }
li { display: block; counter-increment: list-item; }
li:before { content: counters(list-item,'.') ' '; }
```

As posted in the README.
